import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { convertTimestampToDateDashString, hh_mm, parseInvoiceStatus, parseOrderStatus, } from "../utils/libs";
export const OrderDetail = ({ invoiceDetailData, businessData, contentRef, }) => {
    const totalPrice = invoiceDetailData?.products_data.reduce((total, item) => total + item.price * item.amount, 0);
    return (_jsx("div", { style: {
            display: "flex",
            width: "100%",
            height: "100%",
            overflow: "auto",
            alignItems: "center",
            justifyContent: "center",
        }, children: _jsxs("div", { style: {
                display: "flex",
                width: "100%",
                flexDirection: "column",
                alignItems: "center",
                borderRadius: "12px",
                padding: "16px",
                backgroundColor: "white",
            }, children: [_jsxs("div", { ref: contentRef, id: "print-section", style: {
                        width: "100%",
                        display: "flex",
                        justifyContent: "center",
                        alignItems: "center",
                        flexDirection: "column",
                        gap: "16px",
                        padding: "16px",
                    }, children: [_jsxs("div", { style: {
                                display: "flex",
                                justifyContent: "center",
                                alignItems: "center",
                                flexDirection: "column",
                                width: "100%",
                                gap: "8px",
                            }, children: [_jsx("h5", { style: {
                                        textAlign: "center",
                                        fontSize: "14px",
                                        fontWeight: "bold",
                                        lineHeight: "20px",
                                        color: "#262626",
                                    }, children: businessData?.name }), _jsxs("p", { style: {
                                        fontSize: "10px",
                                        lineHeight: "14px",
                                        color: "#4E4E4E",
                                        fontWeight: "600",
                                    }, children: ["\u0110/c: ", businessData?.address] })] }), _jsxs("div", { style: {
                                width: "100%",
                                display: "flex",
                                flexDirection: "column",
                                gap: "16px",
                            }, children: [_jsx("h4", { style: {
                                        textAlign: "center",
                                        fontSize: "16px",
                                        fontWeight: "bold",
                                        lineHeight: "24px",
                                        color: "#262626",
                                    }, children: "HO\u00C1 \u0110\u01A0N B\u00C1N H\u00C0NG" }), _jsxs("div", { style: {
                                        width: "100%",
                                        display: "flex",
                                        flexDirection: "column",
                                        gap: "12px",
                                    }, children: [_jsxs("div", { style: {
                                                width: "100%",
                                                display: "flex",
                                                flexDirection: "row",
                                                alignItems: "center",
                                                justifyContent: "space-between",
                                            }, children: [_jsxs("div", { style: {
                                                        display: "flex",
                                                        flexDirection: "row",
                                                        alignItems: "center",
                                                        justifyContent: "flex-start",
                                                        fontSize: "10px",
                                                        textAlign: "left",
                                                        lineHeight: "14px",
                                                        color: "#262626",
                                                        flex: 1,
                                                        gap: "8px",
                                                    }, children: [_jsx("span", { style: { fontWeight: "600" }, children: "S\u1ED1 ho\u00E1 \u0111\u01A1n:" }), _jsx("span", { style: { fontWeight: "500" }, children: invoiceDetailData?.invoice_data?.invoice_id })] }), _jsxs("div", { style: {
                                                        display: "flex",
                                                        flexDirection: "row",
                                                        alignItems: "center",
                                                        justifyContent: "flex-end",
                                                        fontSize: "10px",
                                                        textAlign: "right",
                                                        lineHeight: "14px",
                                                        color: "#262626",
                                                        flex: 1,
                                                        gap: "8px",
                                                    }, children: [_jsx("span", { style: { fontWeight: "600" }, children: "Ng\u00E0y:" }), _jsx("span", { style: { fontWeight: "500" }, children: convertTimestampToDateDashString(Number(invoiceDetailData?.invoice_data?.updated_at)) })] })] }), _jsxs("div", { style: {
                                                width: "100%",
                                                display: "flex",
                                                flexDirection: "row",
                                                alignItems: "center",
                                                justifyContent: "space-between",
                                            }, children: [_jsxs("div", { style: {
                                                        display: "flex",
                                                        flexDirection: "row",
                                                        alignItems: "center",
                                                        justifyContent: "flex-start",
                                                        fontSize: "10px",
                                                        textAlign: "left",
                                                        lineHeight: "14px",
                                                        color: "#262626",
                                                        flex: 1,
                                                        gap: "8px",
                                                    }, children: [_jsx("span", { style: { fontWeight: "600" }, children: "B\u00E0n:" }), _jsxs("span", { style: { fontWeight: "500" }, children: ["B\u00E0n ", invoiceDetailData?.invoice_data?.table_name] })] }), _jsxs("div", { style: {
                                                        display: "flex",
                                                        flexDirection: "row",
                                                        alignItems: "center",
                                                        justifyContent: "flex-end",
                                                        fontSize: "10px",
                                                        textAlign: "right",
                                                        lineHeight: "14px",
                                                        color: "#262626",
                                                        flex: 1,
                                                        gap: "8px",
                                                    }, children: [_jsx("span", { style: { fontWeight: "600" }, children: "Gi\u1EDD:" }), _jsx("span", { style: { fontWeight: "500" }, children: hh_mm(new Date(invoiceDetailData?.invoice_data?.updated_at || 0)) })] })] }), _jsxs("div", { style: {
                                                width: "100%",
                                                display: "flex",
                                                flexDirection: "row",
                                                alignItems: "center",
                                                justifyContent: "space-between",
                                            }, children: [_jsx("div", { style: {
                                                        display: "flex",
                                                        flexDirection: "row",
                                                        alignItems: "center",
                                                        justifyContent: "flex-start",
                                                        fontSize: "10px",
                                                        textAlign: "left",
                                                        lineHeight: "14px",
                                                        color: "#262626",
                                                        flex: 1,
                                                        gap: "8px",
                                                    }, children: _jsx("span", { style: { fontWeight: "600" }, children: "Tr\u1EA1ng th\u00E1i \u0111\u01A1n:" }) }), _jsx("div", { style: {
                                                        display: "flex",
                                                        flexDirection: "row",
                                                        alignItems: "center",
                                                        justifyContent: "flex-end",
                                                        fontSize: "10px",
                                                        textAlign: "right",
                                                        lineHeight: "14px",
                                                        color: "#262626",
                                                        flex: 1,
                                                        gap: "8px",
                                                    }, children: _jsx("span", { style: { fontWeight: "500" }, children: parseOrderStatus(invoiceDetailData?.invoice_data?.status) }) })] }), _jsxs("div", { style: {
                                                width: "100%",
                                                display: "flex",
                                                flexDirection: "row",
                                                alignItems: "center",
                                                justifyContent: "space-between",
                                            }, children: [_jsx("div", { style: {
                                                        display: "flex",
                                                        flexDirection: "row",
                                                        alignItems: "center",
                                                        justifyContent: "flex-start",
                                                        fontSize: "10px",
                                                        textAlign: "left",
                                                        lineHeight: "14px",
                                                        color: "#262626",
                                                        flex: 1,
                                                        gap: "8px",
                                                    }, children: _jsx("span", { style: { fontWeight: "600" }, children: "Ph\u01B0\u01A1ng th\u1EE9c thanh to\u00E1n:" }) }), _jsx("div", { style: {
                                                        display: "flex",
                                                        flexDirection: "row",
                                                        alignItems: "center",
                                                        justifyContent: "flex-end",
                                                        fontSize: "10px",
                                                        textAlign: "right",
                                                        lineHeight: "14px",
                                                        color: "#262626",
                                                        flex: 1,
                                                        gap: "8px",
                                                    }, children: _jsx("span", { style: { fontWeight: "500" }, children: parseInvoiceStatus(invoiceDetailData?.invoice_data.payment_method) }) })] })] }), _jsxs("div", { style: {
                                        width: "100%",
                                        display: "flex",
                                        flexDirection: "column",
                                        gap: "10px",
                                    }, children: [_jsx("div", { style: {
                                                width: "100%",
                                                height: "1px",
                                                borderTop: "1px solid #8C8C8C",
                                            } }), _jsxs("div", { style: {
                                                width: "100%",
                                                display: "grid",
                                                gridTemplateColumns: "10% 30% 10% 20% 30%",
                                                fontSize: "10px",
                                                lineHeight: "14px",
                                                color: "#262626",
                                                fontWeight: "500",
                                            }, children: [_jsx("span", { style: { textAlign: "left" }, children: "TT" }), _jsx("span", { style: { textAlign: "center" }, children: "T\u00EAn m\u00F3n" }), _jsx("span", { style: { textAlign: "center" }, children: "SL" }), _jsx("span", { style: { textAlign: "center" }, children: "\u0110\u01A1n gi\u00E1" }), _jsx("span", { style: { textAlign: "right" }, children: "Th\u00E0nh ti\u1EC1n" })] }), _jsx("div", { style: {
                                                width: "100%",
                                                height: "1px",
                                                borderTop: "1px solid #8C8C8C",
                                            } })] }), invoiceDetailData?.products_data.map((item, index) => (_jsxs("div", { style: {
                                        width: "100%",
                                        display: "grid",
                                        gridTemplateColumns: "10% 30% 10% 20% 30%",
                                        fontSize: "10px",
                                        lineHeight: "14px",
                                        color: "#262626",
                                        fontWeight: "500",
                                    }, children: [_jsx("span", { style: { textAlign: "left" }, children: index + 1 }), _jsx("span", { style: { textAlign: "center" }, children: item.name }), _jsx("span", { style: { textAlign: "center" }, children: item.amount }), _jsx("span", { style: { textAlign: "center" }, children: item.price }), _jsx("span", { style: { textAlign: "right" }, children: item.price * item.amount })] }, item.product_id))), _jsxs("div", { style: {
                                        width: "100%",
                                        display: "flex",
                                        flexDirection: "row",
                                        alignItems: "center",
                                        justifyContent: "space-between",
                                    }, children: [_jsx("span", { style: {
                                                fontSize: "10px",
                                                fontWeight: "600",
                                                lineHeight: "14px",
                                                color: "#262626",
                                            }, children: "T\u1ED5ng c\u1ED9ng:" }), _jsxs("span", { style: {
                                                fontSize: "14px",
                                                fontWeight: "600",
                                                lineHeight: "20px",
                                                color: "#262626",
                                            }, children: [String(totalPrice), " VND"] })] }), _jsx("div", { style: {
                                        width: "100%",
                                        height: "1px",
                                        borderTop: "1px dashed #D9D9D9",
                                    } }), _jsxs("div", { style: {
                                        width: "100%",
                                        display: "flex",
                                        flexDirection: "row",
                                        alignItems: "center",
                                        justifyContent: "space-between",
                                    }, children: [_jsx("span", { style: {
                                                fontSize: "18px",
                                                fontWeight: "700",
                                                lineHeight: "28px",
                                                color: "#262626",
                                            }, children: "T\u1ED5ng:" }), _jsxs("span", { style: {
                                                fontSize: "18px",
                                                fontWeight: "700",
                                                lineHeight: "28px",
                                                color: "#262626",
                                            }, children: [String(totalPrice), " VND"] })] })] }), _jsxs("div", { style: {
                                width: "100%",
                                display: "flex",
                                flexDirection: "row",
                                alignItems: "center",
                                justifyContent: "center",
                                textAlign: "center",
                                fontSize: "12px",
                                fontWeight: "500",
                                lineHeight: "16px",
                                color: "#262626",
                                fontStyle: "italic",
                            }, children: [businessData?.name, " xin ch\u00E2n th\u00E0nh c\u1EA3m \u01A1n!"] })] }), _jsx("div", { className: "flex w-full flex-col gap-4 p-4", children: _jsx("div", { style: {
                            width: "100%",
                            height: "1px",
                            borderTop: "1px dashed #D9D9D9",
                        } }) })] }) }));
};
